allowBuilds:
  '@thaunknown/yencode': false
  bufferutil: false
  ip-set: set this to true or false
  node-datachannel: false
  protobufjs: false
  utf-8-validate: false
  utp-native: false
minimumReleaseAgeExclude:
  - bittorrent-protocol@5.0.3
  - create-torrent@6.1.2
  - parse-torrent@11.0.21
  - torrent-discovery@11.0.21
  - webtorrent@3.0.6
  - bittorrent-protocol@5.0.4
  - webtorrent@3.0.8
